language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm run test
  - npm run lint
  - npm run build
  - npm run package
  - npm run bundlesize
after_success:
  - npm run coverage
deploy:
  provider: releases
  api_key:
    secure: GITHUB_KEY
  file: ./dist/archive.node.zip
  file: ./dist/archive.browser.zip
  file: ./dist/source.zip
  skip_cleanup: true
  on:
    condition: $TRAVIS_BRANCH == "master"
    tags: true
